import { NextRequest,NextResponse } from "next/server";
import { z,ZodError } from "zod";
import { createPublishPackage,listPublishPackages,publishingPlatforms } from "@/lib/admin/publish-repository";
import { getDramaBySlug } from "@/lib/catalog";
import { snapIsoToTenMinutes } from "@/lib/publish-time";

const platformPack=z.object({source:z.enum(publishingPlatforms),shortCode:z.string().max(100),url:z.string().url(),hook:z.string().max(500),cta:z.string().max(180),hashtags:z.string().max(500),hashtagSource:z.string().max(80),caption:z.string().max(10000)});
const schema=z.object({dramaSlug:z.string().trim().min(1).max(120),episodeNumber:z.number().int().positive().max(999),videoUrl:z.string().url().refine(value=>new URL(value).protocol==="https:"),videoKind:z.enum(["original","hook","upload"]),videoLabel:z.string().trim().max(120).optional(),hookClipId:z.string().uuid().optional(),account:z.string().trim().max(100).optional(),campaign:z.string().trim().max(100).optional(),deliveryMode:z.enum(["draft","now","scheduled"]),scheduledAt:z.string().datetime().transform(snapIsoToTenMinutes).optional(),platforms:z.array(z.enum(publishingPlatforms)).min(1).max(5),preparedPlatforms:z.array(platformPack).max(5).optional()}).refine(input=>input.deliveryMode!=="scheduled"||Boolean(input.scheduledAt),{message:"Scheduled publishing requires a time"}).refine(input=>input.deliveryMode!=="scheduled"||new Date(input.scheduledAt!).getTime()>Date.now(),{message:"Scheduled publishing requires a future time"});
export async function GET(){try{return NextResponse.json({packages:await listPublishPackages()})}catch(error){return NextResponse.json({message:error instanceof Error?error.message:"Could not load publish packages"},{status:503})}}
export async function POST(request:NextRequest){try{const input=schema.parse(await request.json());const drama=await getDramaBySlug(input.dramaSlug);if(!drama)return NextResponse.json({message:"Published drama not found"},{status:404});const siteUrl=process.env.NEXT_PUBLIC_SITE_URL||new URL(request.url).origin;return NextResponse.json({package:await createPublishPackage({...input,title:drama.title,promoCode:drama.promoCode||drama.publicCode,contentPromotionUrl:drama.contentPromotionUrl,description:drama.description,tags:drama.tags,siteUrl})},{status:201})}catch(error){if(error instanceof ZodError)return NextResponse.json({message:"Check the video, episode, schedule, and platforms"},{status:400});return NextResponse.json({message:error instanceof Error?error.message:"Could not create publish package"},{status:503})}}
