import "server-only";
import crypto,{randomUUID} from "crypto";
import {mkdir,readFile,rename,writeFile} from "fs/promises";
import path from "path";
import {getSupabaseConfig} from "./supabase-config";
import type {HookCandidate,HookJob,HookJobStatus,HookSourceAsset} from "./hook-job-types";
const pipelineVersion="hook-worker-v7-prism-ending";
function filePath(){return process.env.HOOK_JOB_FILE||path.join(process.cwd(),"data","hook-jobs.json")}
async function localRows():Promise<HookJob[]>{try{const rows=JSON.parse(await readFile(filePath(),"utf8"));return Array.isArray(rows)?rows:[]}catch{return[]}}
async function writeLocal(rows:HookJob[]){const file=filePath();await mkdir(path.dirname(file),{recursive:true});const temp=`${file}.tmp`;await writeFile(temp,JSON.stringify(rows,null,2),{mode:0o600});await rename(temp,file)}
async function request(pathname:string,init:RequestInit={}){const config=getSupabaseConfig();const response=await fetch(`${config.url}/rest/v1/${pathname}`,{...init,headers:{apikey:config.key,Authorization:`Bearer ${config.key}`,"Content-Type":"application/json",...init.headers},cache:"no-store"});if(!response.ok)throw new Error(`Supabase ${response.status}: ${(await response.text()).slice(0,220)}`);return response.status===204?null:response.json()}
type JobRow={id:string;idempotency_key:string;drama_id:string;drama_slug:string;source_episodes:number[];source_assets:HookSourceAsset[];settings:Record<string,unknown>;creative_direction?:string;direction_schema?:Record<string,unknown>;direction_parser_version?:string;direction_model_version?:string;pipeline_version:string;status:HookJobStatus;progress:number;error_category?:string;error_message?:string;retry_count:number;max_retries:number;lease_owner?:string;lease_expires_at?:string;heartbeat_at?:string;created_at:string;updated_at:string;completed_at?:string};
type CandidateRow={id:string;rank:number;title:string;hook_type:string;source_ranges:HookCandidate["sourceRanges"];rendered_ranges:HookCandidate["renderedRanges"];score:number;score_components:Record<string,number>;rationale:string;risk_level:HookCandidate["riskLevel"];risk_assessment:Record<string,unknown>;direction_match_score?:number;direction_evidence?:Record<string,unknown>;cover_source_timestamp:number;draft_object_key?:string;draft_url?:string;duration_seconds?:number;width?:number;height?:number;video_codec?:string;audio_codec?:string;size_bytes?:number;qa_results?:Record<string,unknown>;review_state:HookCandidate["reviewState"]};
function mapCandidate(row:CandidateRow):HookCandidate{return{id:row.id,rank:row.rank,title:row.title,hookType:row.hook_type,sourceRanges:row.source_ranges,renderedRanges:row.rendered_ranges,score:Number(row.score),scoreComponents:row.score_components,rationale:row.rationale,riskLevel:row.risk_level,riskAssessment:row.risk_assessment,directionMatchScore:row.direction_match_score==null?undefined:Number(row.direction_match_score),directionEvidence:row.direction_evidence,coverSourceTimestamp:Number(row.cover_source_timestamp),draftObjectKey:row.draft_object_key,draftUrl:row.draft_url,durationSeconds:row.duration_seconds?Number(row.duration_seconds):undefined,width:row.width,height:row.height,videoCodec:row.video_codec,audioCodec:row.audio_codec,sizeBytes:row.size_bytes?Number(row.size_bytes):undefined,qaResults:row.qa_results,reviewState:row.review_state}}
function mapJob(row:JobRow,candidates:HookCandidate[]=[]):HookJob{return{id:row.id,idempotencyKey:row.idempotency_key,dramaId:row.drama_id,dramaSlug:row.drama_slug,sourceEpisodes:row.source_episodes,sourceAssets:row.source_assets,settings:row.settings,creativeDirection:row.creative_direction||String(row.settings?.creativeDirection||""),directionSchema:row.direction_schema||{},directionParserVersion:row.direction_parser_version||"rule-v1",directionModelVersion:row.direction_model_version,pipelineVersion:row.pipeline_version,status:row.status,progress:row.progress,errorCategory:row.error_category,errorMessage:row.error_message,retryCount:row.retry_count,maxRetries:row.max_retries,leaseOwner:row.lease_owner,leaseExpiresAt:row.lease_expires_at,heartbeatAt:row.heartbeat_at,createdAt:row.created_at,updatedAt:row.updated_at,completedAt:row.completed_at,candidates}}
export function hookIdempotency(input:{dramaId:string;sourceEpisodes:number[];settings:Record<string,unknown>}){return crypto.createHash("sha256").update(JSON.stringify({dramaId:input.dramaId,sourceEpisodes:[...input.sourceEpisodes].sort((a,b)=>a-b),settings:input.settings,pipelineVersion})).digest("hex")}
export async function createHookJob(input:{dramaId:string;dramaSlug:string;sourceAssets:HookSourceAsset[];settings:Record<string,unknown>;forceNew?:boolean}){const sourceEpisodes=input.sourceAssets.map(asset=>asset.episodeNumber);const creativeDirection=String(input.settings.creativeDirection||"").trim();const baseSettings={...input.settings,creativeDirection};const idempotencyKey=input.forceNew?`${hookIdempotency({dramaId:input.dramaId,sourceEpisodes,settings:baseSettings})}-${crypto.randomUUID()}`:hookIdempotency({dramaId:input.dramaId,sourceEpisodes,settings:baseSettings});const config=getSupabaseConfig();if(!config.configured){const rows=await localRows();const existing=rows.find(row=>row.idempotencyKey===idempotencyKey&&!['failed','canceled'].includes(row.status));if(existing)return existing;const now=new Date().toISOString();const job:HookJob={id:randomUUID(),idempotencyKey,dramaId:input.dramaId,dramaSlug:input.dramaSlug,sourceEpisodes,sourceAssets:input.sourceAssets,settings:baseSettings,creativeDirection,directionSchema:{},directionParserVersion:"rule-v1",pipelineVersion,status:"queued",progress:0,retryCount:0,maxRetries:3,createdAt:now,updatedAt:now,candidates:[]};await writeLocal([job,...rows]);return job}const payload={idempotency_key:idempotencyKey,drama_id:input.dramaId,drama_slug:input.dramaSlug,source_episodes:sourceEpisodes,source_assets:input.sourceAssets,settings:baseSettings,creative_direction:creativeDirection,direction_schema:{},direction_parser_version:"rule-v1",pipeline_version:pipelineVersion,status:"queued",progress:0};const rows=await request("hook_generation_jobs?on_conflict=idempotency_key",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates,return=representation"},body:JSON.stringify(payload)}) as JobRow[];if(rows.length)return mapJob(rows[0]);const found=await request(`hook_generation_jobs?idempotency_key=eq.${idempotencyKey}&select=*`) as JobRow[];return mapJob(found[0])}
export async function getHookJob(id:string){const config=getSupabaseConfig();if(!config.configured)return(await localRows()).find(row=>row.id===id)||null;const rows=await request(`hook_generation_jobs?id=eq.${encodeURIComponent(id)}&select=*`) as JobRow[];if(!rows[0])return null;const candidates=await request(`hook_candidates?job_id=eq.${encodeURIComponent(id)}&select=*&order=rank`) as CandidateRow[];return mapJob(rows[0],candidates.map(mapCandidate))}
export async function listHookJobs(dramaId?:string,limit=10){const config=getSupabaseConfig();if(!config.configured){const rows=(await localRows()).filter(row=>!dramaId||row.dramaId===dramaId).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,limit);return rows}const filter=dramaId?`&drama_id=eq.${encodeURIComponent(dramaId)}`:"";const rows=await request(`hook_generation_jobs?select=*&order=created_at.desc&limit=${Math.max(1,Math.min(limit,100))}${filter}`) as JobRow[];return Promise.all(rows.map(async row=>{const candidates=await request(`hook_candidates?job_id=eq.${encodeURIComponent(row.id)}&select=*&order=rank`) as CandidateRow[];return mapJob(row,candidates.map(mapCandidate))}))}
export async function setHookJobAction(id:string,action:"cancel"|"retry"){const config=getSupabaseConfig();if(!config.configured){const rows=await localRows();const job=rows.find(row=>row.id===id);if(!job)throw new Error("Hook job not found");if(action==="cancel"&&!['review_ready','no_result','failed'].includes(job.status)){job.status="canceled";job.completedAt=new Date().toISOString()}if(action==="retry"&&['failed','canceled'].includes(job.status)){job.status="queued";job.progress=0;job.errorCategory=undefined;job.errorMessage=undefined;job.retryCount+=1;job.completedAt=undefined}job.updatedAt=new Date().toISOString();await writeLocal(rows);return job}const current=await getHookJob(id);if(!current)throw new Error("Hook job not found");const allowed=action==="cancel"?!['review_ready','no_result','failed','canceled'].includes(current.status):['failed','canceled'].includes(current.status)&&current.retryCount<current.maxRetries;if(!allowed)throw new Error(`Job cannot ${action} from ${current.status}`);const body=action==="cancel"?{status:"canceled",completed_at:new Date().toISOString(),lease_owner:null,lease_expires_at:null}:{status:"queued",progress:0,error_category:null,error_message:null,retry_count:current.retryCount+1,completed_at:null,next_attempt_at:new Date().toISOString(),lease_owner:null,lease_expires_at:null};const rows=await request(`hook_generation_jobs?id=eq.${id}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(body)}) as JobRow[];return mapJob(rows[0])}
export async function leaseNextHookJob(workerId:string,leaseSeconds=120){const config=getSupabaseConfig();if(!config.configured){const rows=await localRows();const now=Date.now();const job=rows.find(row=>row.status==="queued"||((row.leaseExpiresAt?Date.parse(row.leaseExpiresAt):Infinity)<now&&!['review_ready','no_result','failed','canceled'].includes(row.status)));if(!job)return null;job.status="downloading";job.progress=Math.max(job.progress,2);job.leaseOwner=workerId;job.heartbeatAt=new Date().toISOString();job.leaseExpiresAt=new Date(now+leaseSeconds*1000).toISOString();job.updatedAt=job.heartbeatAt;await writeLocal(rows);return job}const rows=await request("rpc/lease_hook_generation_job",{method:"POST",body:JSON.stringify({p_worker_id:workerId,p_lease_seconds:leaseSeconds})}) as JobRow[];return rows[0]?mapJob(rows[0]):null}
export async function updateLocalWorkerJob(id:string,workerId:string,input:{status:HookJobStatus;progress:number;errorCategory?:string;errorMessage?:string;directionSchema?:Record<string,unknown>;candidates?:HookCandidate[]}){const config=getSupabaseConfig();if(config.configured)throw new Error("Production worker updates require the database worker RPC");const rows=await localRows();const job=rows.find(row=>row.id===id);if(!job||job.leaseOwner!==workerId)throw new Error("Lease not owned");job.status=input.status;job.progress=input.progress;job.errorCategory=input.errorCategory;job.errorMessage=input.errorMessage;if(input.directionSchema)job.directionSchema=input.directionSchema;if(input.candidates)job.candidates=input.candidates;job.heartbeatAt=new Date().toISOString();job.leaseExpiresAt=new Date(Date.now()+120000).toISOString();job.updatedAt=job.heartbeatAt;if(['review_ready','no_result','failed','canceled'].includes(job.status))job.completedAt=job.updatedAt;await writeLocal(rows);return job}
