import "server-only";
import { getSupabaseConfig } from "./supabase-config";
import { createShortLink } from "./analytics-repository";

export const publishingPlatforms=["tiktok","instagram","youtube","facebook","x"] as const;
export type PublishingPlatform=typeof publishingPlatforms[number];
type PlatformPack={source:PublishingPlatform;shortCode:string;url:string;hook:string;caption:string};
type Row={id:string;drama_slug:string;episode_number:number;video_url:string;video_kind?:"original"|"hook"|"upload";video_label?:string;hook_clip_id?:string;account:string;campaign:string;scheduled_at?:string;status:string;platforms:PlatformPack[];metricool_post_ids:Record<string,string>;yixiaoer_video?:Record<string,unknown>;yixiaoer_payloads?:Record<string,unknown>;yixiaoer_results?:Record<string,unknown>;yixiaoer_action?:"validate"|"publish";yixiaoer_accounts?:Record<string,string>;yixiaoer_progress?:number;yixiaoer_error?:string;yixiaoer_lease_owner?:string;yixiaoer_lease_expires_at?:string;yixiaoer_updated_at?:string;created_at:string;updated_at:string};

async function request(path:string,init:RequestInit={}){const config=getSupabaseConfig();if(!config.configured)throw new Error("Supabase is not configured");const response=await fetch(`${config.url}/rest/v1/${path}`,{...init,headers:{apikey:config.key,Authorization:`Bearer ${config.key}`,"Content-Type":"application/json",...init.headers},cache:"no-store"});if(!response.ok)throw new Error(`Supabase ${response.status}: ${(await response.text()).slice(0,220)}`);return response.status===204?null:response.json()}
function safe(row:Row){return{id:row.id,dramaSlug:row.drama_slug,episodeNumber:row.episode_number,videoUrl:row.video_url,videoKind:row.video_kind||"original",videoLabel:row.video_label,hookClipId:row.hook_clip_id,account:row.account,campaign:row.campaign,scheduledAt:row.scheduled_at,status:row.status,platforms:row.platforms,metricoolPostIds:row.metricool_post_ids,yixiaoerVideo:row.yixiaoer_video||{},yixiaoerPayloads:row.yixiaoer_payloads||{},yixiaoerResults:row.yixiaoer_results||{},yixiaoerAction:row.yixiaoer_action,yixiaoerAccounts:row.yixiaoer_accounts||{},yixiaoerProgress:row.yixiaoer_progress||0,yixiaoerError:row.yixiaoer_error,yixiaoerUpdatedAt:row.yixiaoer_updated_at,createdAt:row.created_at}}
function shorten(value:string,max:number){const clean=value.replace(/\s+/g," ").trim();if(clean.length<=max)return clean;return `${clean.slice(0,max-1).replace(/[,;:\s]+$/g,"")}…`}
function hashTag(value:string){return value.normalize("NFKD").replace(/[^a-zA-Z0-9]+/g,"").slice(0,28)}
function copyFor(source:PublishingPlatform,title:string,episode:number,url:string,promoCode:string,description:string,tags:string[]){
  const firstSentence=description.match(/^.+?[.!?](?:\s|$)/)?.[0]||description;
  const hookLead:Record<PublishingPlatform,string>={tiktok:"😱 Wait—this changes everything:",instagram:"✨ The moment everything changed:",youtube:"👀 You won't expect what happens next:",facebook:"💔 One decision changed the entire story:",x:"😳 This scene changes everything:"};
  const hook=`${hookLead[source]} ${shorten(firstSentence,source==="x"?65:150)}`;
  const titleTag=hashTag(title);const tagSet=["#ReelShort","#DramaClips","#ShortDrama",...(source==="youtube"?["#Shorts"]:[]),...(titleTag?[`#${titleTag}`]:[]),...tags.slice(0,2).map(tag=>`#${hashTag(tag)}`).filter(tag=>tag!=="#")];
  const top=`🔥 Watch now 👉 ${url}`;
  const code=`🔍 Search “${promoCode}” in ReelShort or DramaClips`;
  if(source==="x"){
    const fixed=`${top}\n${hook}\n${code}\n#ReelShort #ShortDrama`;
    return{hook,caption:shorten(fixed,280)};
  }
  const descriptionLimit:Record<Exclude<PublishingPlatform,"x">,number>={tiktok:420,instagram:700,youtube:900,facebook:1000};
  const story=shorten(description,descriptionLimit[source]);
  const caption=[top,"🌟 Continue the story here",hook,`🎬 ${title} · EP ${episode}`,"👉🏻 📲 Download the ReelShort app",code,`✨ ${story}`,tagSet.join(" ")].join("\n");
  return{hook,caption};
}

export async function createPublishPackage(input:{dramaSlug:string;title:string;promoCode:string;description:string;tags:string[];episodeNumber:number;videoUrl:string;videoKind:"original"|"hook"|"upload";videoLabel?:string;hookClipId?:string;account?:string;campaign?:string;scheduledAt?:string;platforms:PublishingPlatform[];siteUrl:string}){
  await request("publish_packages?select=id&limit=0");
  const packs:PlatformPack[]=[];
  for(const source of input.platforms){const link=await createShortLink({dramaSlug:input.dramaSlug,source,account:input.account,campaign:input.campaign,clip:`ep-${String(input.episodeNumber).padStart(2,"0")}`});const url=`${input.siteUrl.replace(/\/$/,"")}/x/${link.code}`;packs.push({source,shortCode:link.code,url,...copyFor(source,input.title,input.episodeNumber,url,input.promoCode,input.description,input.tags)})}
  const rows=await request("publish_packages",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({drama_slug:input.dramaSlug,episode_number:input.episodeNumber,video_url:input.videoUrl,video_kind:input.videoKind,video_label:input.videoLabel||null,hook_clip_id:input.hookClipId||null,account:input.account||"main",campaign:input.campaign||"organic",scheduled_at:input.scheduledAt||null,status:"ready",platforms:packs})}) as Row[];
  return safe(rows[0]);
}
export async function listPublishPackages(){const rows=await request("publish_packages?select=*&order=created_at.desc&limit=50") as Row[];return rows.map(safe)}
export async function getLatestPublishPackage(){const rows=await request("publish_packages?select=*&order=created_at.desc&limit=1") as Row[];return rows[0]?safe(rows[0]):null}
export async function getPublishPackage(id:string){const rows=await request(`publish_packages?id=eq.${encodeURIComponent(id)}&select=*&limit=1`) as Row[];return rows[0]?safe(rows[0]):null}
export async function updatePublishPackagePlatforms(id:string,platforms:PlatformPack[]){const rows=await request(`publish_packages?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({platforms,updated_at:new Date().toISOString()})}) as Row[];if(!rows[0])throw new Error("Publish package not found");return safe(rows[0])}
export async function updatePublishPackageYixiaoer(id:string,input:{status?:string;video?:Record<string,unknown>;payloads?:Record<string,unknown>;results?:Record<string,unknown>}){const body:Record<string,unknown>={updated_at:new Date().toISOString()};if(input.status)body.status=input.status;if(input.video)body.yixiaoer_video=input.video;if(input.payloads)body.yixiaoer_payloads=input.payloads;if(input.results)body.yixiaoer_results=input.results;const rows=await request(`publish_packages?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(body)}) as Row[];if(!rows[0])throw new Error("Publish package not found");return safe(rows[0])}
export async function enqueueYixiaoerPackage(id:string,input:{action:"validate"|"publish";accounts:Record<string,string>}){const rows=await request(`publish_packages?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status:input.action==="validate"?"validating":"publishing",yixiaoer_action:input.action,yixiaoer_accounts:input.accounts,yixiaoer_progress:1,yixiaoer_error:null,yixiaoer_lease_owner:null,yixiaoer_lease_expires_at:null,yixiaoer_updated_at:new Date().toISOString(),updated_at:new Date().toISOString()})}) as Row[];if(!rows[0])throw new Error("Publish package not found");return safe(rows[0])}
export async function requestCancelYixiaoerPackage(id:string){const item=await getPublishPackage(id);if(!item)throw new Error("Publish package not found");if(!item.yixiaoerAction)throw new Error("No Yixiaoer operation is running");const results={...item.yixiaoerResults,_control:{cancelRequested:true,requestedAt:new Date().toISOString()}};const rows=await request(`publish_packages?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({yixiaoer_results:results,yixiaoer_updated_at:new Date().toISOString(),updated_at:new Date().toISOString()})}) as Row[];return safe(rows[0])}
export async function leaseYixiaoerPackage(workerId:string,leaseSeconds=600){const rows=await request("rpc/lease_yixiaoer_publish_job",{method:"POST",body:JSON.stringify({p_worker_id:workerId,p_lease_seconds:leaseSeconds})}) as Row[];return rows[0]?safe(rows[0]):null}
export async function updateYixiaoerWorkerPackage(id:string,workerId:string,input:{status:string;progress:number;video?:Record<string,unknown>;payloads?:Record<string,unknown>;results?:Record<string,unknown>;error?:string;terminal?:boolean}){const current=await getPublishPackage(id);const control=current?.yixiaoerResults?._control;const body:Record<string,unknown>={status:input.status,yixiaoer_progress:input.progress,yixiaoer_error:input.error||null,yixiaoer_updated_at:new Date().toISOString(),updated_at:new Date().toISOString(),yixiaoer_lease_expires_at:input.terminal?null:new Date(Date.now()+600000).toISOString()};if(input.video)body.yixiaoer_video=input.video;if(input.payloads)body.yixiaoer_payloads=input.payloads;if(input.results)body.yixiaoer_results=control?{...input.results,_control:control}:input.results;if(input.terminal){body.yixiaoer_action=null;body.yixiaoer_lease_owner=null}const rows=await request(`publish_packages?id=eq.${encodeURIComponent(id)}&yixiaoer_lease_owner=eq.${encodeURIComponent(workerId)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(body)}) as Row[];if(!rows[0])throw new Error("Yixiaoer lease not owned");return safe(rows[0])}
