import "server-only";
import crypto from "node:crypto";
import {deleteExpiredHookDrafts,listExpiredHookDrafts} from "./r2";
import {getSupabaseConfig} from "./supabase-config";
type Row=Record<string,unknown>;
export type CleanupPlan={fingerprint:string;generatedAt:string;totals:{records:number;r2Drafts:number;r2Bytes:number};categories:{publishPackages:{id:string;label:string;reason:string}[];hookJobs:{id:string;label:string;reason:string}[];vizardProjects:{id:string;label:string;reason:string}[];r2Drafts:{key:string;bytes:number;modifiedAt:string;reason:string}[]};protected:{activeJobs:number;savedJobs:number;referencedHookClips:number;referencedDrafts:number;vizardWithAssets:number}};
async function request(path:string,init:RequestInit={}){const config=getSupabaseConfig();if(!config.configured)throw new Error("Supabase is not configured");const response=await fetch(`${config.url}/rest/v1/${path}`,{...init,headers:{apikey:config.key,Authorization:`Bearer ${config.key}`,"Content-Type":"application/json",...init.headers},cache:"no-store"});if(!response.ok)throw new Error(`Supabase cleanup returned ${response.status}: ${(await response.text()).slice(0,180)}`);return response.status===204?null:response.json()}
function hashPlan(value:Omit<CleanupPlan,"fingerprint">){const targets={packages:value.categories.publishPackages.map(item=>item.id).sort(),jobs:value.categories.hookJobs.map(item=>item.id).sort(),vizard:value.categories.vizardProjects.map(item=>item.id).sort(),drafts:value.categories.r2Drafts.map(item=>item.key).sort()};return crypto.createHash("sha256").update(JSON.stringify(targets)).digest("hex")}
export async function createStorageCleanupPlan():Promise<CleanupPlan>{
 const now=Date.now(),sevenDays=new Date(now-7*864e5),thirtyDays=new Date(now-30*864e5);
 const [packages,clips,jobs,candidates,vizardProjects,vizardAssets]=await Promise.all([
  request("publish_packages?select=id,drama_slug,video_label,status,created_at,yixiaoer_video,yixiaoer_action,hook_clip_id") as Promise<Row[]>,request("hook_clips?select=id,job_id") as Promise<Row[]>,request("hook_generation_jobs?select=id,drama_slug,source_episodes,status,created_at") as Promise<Row[]>,request("hook_candidates?select=job_id,draft_object_key,review_state") as Promise<Row[]>,request("vizard_projects?select=id,project_name,status,submitted_at") as Promise<Row[]>,request("vizard_assets?select=project_id") as Promise<Row[]>,
 ]);
 const referencedHookClipIds=new Set(packages.map(item=>String(item.hook_clip_id||"")).filter(Boolean));
 const savedJobs=new Set(clips.map(item=>String(item.job_id||"")).filter(Boolean)),referencedJobs=new Set(clips.filter(item=>referencedHookClipIds.has(String(item.id||""))).map(item=>String(item.job_id||"")).filter(Boolean)),terminalJobs=new Set(["review_ready","no_result","failed","canceled"]);
 const removableJobIds=new Set(jobs.filter(item=>terminalJobs.has(String(item.status))&&Date.parse(String(item.created_at))<sevenDays.getTime()&&!savedJobs.has(String(item.id))&&!referencedJobs.has(String(item.id))).map(item=>String(item.id)));
 const protectedDraftKeys=new Set(candidates.filter(item=>!removableJobIds.has(String(item.job_id))).map(item=>String(item.draft_object_key||"")).filter(Boolean));
 const drafts=await listExpiredHookDrafts(sevenDays,protectedDraftKeys),projectsWithAssets=new Set(vizardAssets.map(item=>String(item.project_id||"")).filter(Boolean));
 const categories={
  publishPackages:packages.filter(item=>!item.yixiaoer_action&&["ready","failed"].includes(String(item.status))&&Date.parse(String(item.created_at))<(Object.keys((item.yixiaoer_video as Row)||{}).length?thirtyDays:sevenDays).getTime()).map(item=>({id:String(item.id),label:`${item.drama_slug} · ${item.video_label||item.status}`,reason:Object.keys((item.yixiaoer_video as Row)||{}).length?"Inactive uploaded dry-run older than 30 days":"Unpublished result older than 7 days"})),
  hookJobs:jobs.filter(item=>removableJobIds.has(String(item.id))).map(item=>({id:String(item.id),label:`${item.drama_slug} · EP ${Array.isArray(item.source_episodes)?item.source_episodes.join(", "):"?"}`,reason:`${String(item.status).replaceAll("_"," ")} · no Saved Hook · older than 7 days`})),
  vizardProjects:vizardProjects.filter(item=>["failed","archived"].includes(String(item.status))&&Date.parse(String(item.submitted_at))<thirtyDays.getTime()&&!projectsWithAssets.has(String(item.id))).map(item=>({id:String(item.id),label:String(item.project_name||item.id),reason:`${item.status} · no saved Vizard asset · older than 30 days`})),
  r2Drafts:drafts.map(item=>({...item,reason:"Expired hook draft with no retained job reference"})),
 };
 const value:Omit<CleanupPlan,"fingerprint">={generatedAt:new Date().toISOString(),totals:{records:categories.publishPackages.length+categories.hookJobs.length+categories.vizardProjects.length,r2Drafts:categories.r2Drafts.length,r2Bytes:categories.r2Drafts.reduce((total,item)=>total+item.bytes,0)},categories,protected:{activeJobs:jobs.filter(item=>!terminalJobs.has(String(item.status))).length,savedJobs:savedJobs.size,referencedHookClips:referencedHookClipIds.size,referencedDrafts:protectedDraftKeys.size,vizardWithAssets:projectsWithAssets.size}};
 return{fingerprint:hashPlan(value),...value};
}
function ids(items:{id:string}[]){return items.map(item=>item.id).join(",")}
export async function executeStorageCleanup(expectedFingerprint:string){const plan=await createStorageCleanupPlan();if(plan.fingerprint!==expectedFingerprint)throw new Error("Cleanup plan changed. Scan again before deleting anything.");await deleteExpiredHookDrafts(plan.categories.r2Drafts.map(item=>item.key));if(plan.categories.publishPackages.length)await request(`publish_packages?id=in.(${ids(plan.categories.publishPackages)})`,{method:"DELETE"});if(plan.categories.hookJobs.length)await request(`hook_generation_jobs?id=in.(${ids(plan.categories.hookJobs)})`,{method:"DELETE"});if(plan.categories.vizardProjects.length)await request(`vizard_projects?id=in.(${ids(plan.categories.vizardProjects)})`,{method:"DELETE"});return plan}
