import "server-only";import type { DramaDraftInput,DramaUpdateInput } from "./drama-schema";import type { StoredDramaDraft } from "./draft-repository";import { encryptSensitive } from "./encryption";import { getSupabaseConfig } from "./supabase-config";
type DbRow={id:string;status:"draft"|"published";title:string;slug:string;public_code:string;promo_code:string;language:string;tags:string[];description:string;cover_url:string;episodes:DramaDraftInput["episodes"];cps_url_encrypted:string;created_at:string;published_at?:string};
async function request(path:string,init:RequestInit={}){const config=getSupabaseConfig();if(!config.configured)throw new Error("Supabase is not configured");const response=await fetch(`${config.url}/rest/v1/${path}`,{...init,headers:{apikey:config.key,Authorization:`Bearer ${config.key}`,"Content-Type":"application/json",...init.headers},cache:"no-store"});if(!response.ok)throw new Error(`Supabase ${response.status}: ${(await response.text()).slice(0,180)}`);if(response.status===204)return null;return response.json()}
function fromRow(row:DbRow):StoredDramaDraft{return{id:row.id,status:row.status,title:row.title,slug:row.slug,publicCode:row.public_code,promoCode:row.promo_code,language:row.language,tags:row.tags,description:row.description,coverUrl:row.cover_url,episodes:row.episodes,cpsUrlEncrypted:row.cps_url_encrypted,createdAt:row.created_at,publishedAt:row.published_at}}
function safe(row:StoredDramaDraft){return{id:row.id,status:row.status,title:row.title,slug:row.slug,publicCode:row.publicCode,promoCode:row.promoCode,coverUrl:row.coverUrl,episodeCount:row.episodes.length,destinationHost:"reelslink.com",createdAt:row.createdAt,publishedAt:row.publishedAt}}
export async function saveSupabaseDraft(input:DramaDraftInput){const {cpsUrl,...rest}=input;const payload={status:"draft",title:rest.title,slug:rest.slug,public_code:rest.publicCode,promo_code:rest.promoCode,language:rest.language,tags:rest.tags,description:rest.description,cover_url:rest.coverUrl,episodes:rest.episodes,cps_url_encrypted:encryptSensitive(cpsUrl)};const rows=await request("drama_bundles",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)}) as DbRow[];return safe(fromRow(rows[0]))}
export async function listSupabaseDrafts(){const rows=await request("drama_bundles?select=*&order=created_at.desc") as DbRow[];return rows.map(row=>safe(fromRow(row)))}
export async function publishSupabaseDraft(id:string){const rows=await request(`drama_bundles?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({status:"published",published_at:new Date().toISOString(),updated_at:new Date().toISOString()})}) as DbRow[];if(!rows.length)throw new Error("Draft not found");return safe(fromRow(rows[0]))}
export async function getSupabasePublished(){const rows=await request("drama_bundles?status=eq.published&select=*&order=published_at.desc") as DbRow[];return rows.map(fromRow)}
export async function getSupabaseDramaForEdit(id:string){const rows=await request(`drama_bundles?id=eq.${encodeURIComponent(id)}&select=*`) as DbRow[];if(!rows.length)return null;const row=fromRow(rows[0]);const {cpsUrlEncrypted,...rest}=row;return{...rest,hasCpsUrl:Boolean(cpsUrlEncrypted)}}
export async function updateSupabaseDrama(id:string,input:DramaUpdateInput){const {cpsUrl,...rest}=input;const payload:Record<string,unknown>={title:rest.title,slug:rest.slug,public_code:rest.publicCode,promo_code:rest.promoCode,language:rest.language,tags:rest.tags,description:rest.description,cover_url:rest.coverUrl,episodes:rest.episodes,updated_at:new Date().toISOString()};if(cpsUrl)payload.cps_url_encrypted=encryptSensitive(cpsUrl);const rows=await request(`drama_bundles?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(payload)}) as DbRow[];if(!rows.length)throw new Error("Drama not found");return safe(fromRow(rows[0]))}
export async function deleteSupabaseDrama(id:string){await request(`drama_bundles?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"})}
