"use client";

import {Check,ChevronLeft,ChevronRight,LoaderCircle,Play,Scissors,Trash2} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {VizardStudio} from "./vizard-studio";

type Episode={episodeNumber:number;videoUrl:string};
type Asset={id:string;kind:"clip"|"candidate"|"vizard";jobId?:string;dramaId:string;dramaSlug:string;dramaTitle:string;coverUrl:string;title:string;sourceEpisodes:number[];videoUrl:string;durationSeconds:number;generator:"Built-in"|"Vizard";status:"published"|"publishing"|"scheduled"|"failed"|"ready";createdAt:string};
type Source={id:string;title:string;slug:string;language:string;coverUrl:string;episodes:Episode[];analyzedEpisodes:number[]};
type Job={id:string;status:string;progress:number;errorMessage?:string};
const statusLabel={published:"Published",publishing:"Publishing",scheduled:"Scheduled",failed:"Failed",ready:"Saved"};

export function HookStudioDashboard({sources,assets}:{sources:Source[];assets:Asset[]}){
 const [pageSize,setPageSize]=useState(5),[page,setPage]=useState(1),[selectedId,setSelectedId]=useState<string|null>(null),[sourceId,setSourceId]=useState(sources[0]?.id||""),[episodes,setEpisodes]=useState<number[]>([]),[direction,setDirection]=useState(""),[method,setMethod]=useState<"built-in"|"vizard">("built-in"),[busy,setBusy]=useState(false),[job,setJob]=useState<Job|null>(null),[error,setError]=useState("");
 const source=sources.find(item=>item.id===sourceId);const selected=assets.find(item=>item.id===selectedId);const pages=Math.max(1,Math.ceil(assets.length/pageSize));const rows=assets.slice((page-1)*pageSize,page*pageSize);
 useEffect(()=>{if(page>pages)setPage(pages)},[page,pages]);
 useEffect(()=>{if(!job||["review_ready","no_result","failed","canceled"].includes(job.status))return;const timer=window.setInterval(async()=>{const response=await fetch(`/api/admin/hooks/jobs?id=${encodeURIComponent(job.id)}`,{cache:"no-store"});const json=await response.json();if(response.ok)setJob(json.job)},2500);return()=>window.clearInterval(timer)},[job]);
 function toggleEpisode(number:number){setEpisodes(items=>items.includes(number)?items.filter(item=>item!==number):items.length<5?[...items,number].sort((a,b)=>a-b):items)}
 async function generate(){if(!source||!episodes.length)return;setBusy(true);setError("");try{const response=await fetch("/api/admin/hooks/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dramaId:source.id,episodeNumbers:episodes,forceNew:true,settings:{maxHooks:2,coverDuration:.1,hookTitle:true,creativeDirection:direction}})});const json=await response.json();if(!response.ok)throw new Error(json.message||"Could not start generation");setJob(json.job)}catch(reason){setError(reason instanceof Error?reason.message:"Could not start generation")}finally{setBusy(false)}}
 async function remove(asset:Asset){if(!window.confirm(`Delete “${asset.title}”? This removes the generated video and record.`))return;setBusy(true);setError("");try{const url=asset.kind==="vizard"?`/api/admin/vizard/assets/${asset.id}`:asset.kind==="clip"?`/api/admin/hooks/clips/${asset.id}`:`/api/admin/hooks/jobs/${asset.jobId}/candidates/${asset.id}`;const response=await fetch(url,asset.kind==="vizard"?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delete"})}:{method:"DELETE"});const json=await response.json();if(!response.ok)throw new Error(json.message||"Could not delete hook");window.location.reload()}catch(reason){setError(reason instanceof Error?reason.message:"Could not delete hook")}finally{setBusy(false)}}
 if(!sources.length)return <div className="admin-empty"><Scissors/><h2>No published dramas</h2></div>;
 return <div className="hook-dashboard">
  <section className="hook-assets-panel"><div className="hook-section-title"><div><span>01 · Hook library</span><h2>Generated hooks</h2></div><div><b>{assets.length}</b><small>saved assets</small></div></div><div className="hook-table-tools"><label>Rows <select value={pageSize} onChange={event=>{setPageSize(Number(event.target.value));setPage(1)}}><option value="5">5</option><option value="10">10</option></select></label><small>Click a row to preview. Generated hooks are saved automatically.</small></div><div className="hook-asset-head"><b>Drama / hook</b><b>Episodes</b><b>Generator</b><b>Status</b><b>Created</b></div>{rows.map(asset=><div className={`hook-asset-wrap${selectedId===asset.id?" open":""}`} key={`${asset.kind}-${asset.id}`}><button className="hook-asset-row" onClick={()=>setSelectedId(selectedId===asset.id?null:asset.id)}><span><img src={asset.coverUrl} alt=""/><i><strong>{asset.dramaTitle}</strong><small>{asset.title}</small></i></span><span>EP {asset.sourceEpisodes.join(", ")}</span><span>{asset.generator}</span><span><em className={`asset-status ${asset.status}`}>{statusLabel[asset.status]}</em></span><span>{asset.createdAt.slice(0,10)}</span></button>{selectedId===asset.id&&<div className="hook-preview"><video src={asset.videoUrl} controls preload="metadata" playsInline/><div><span className={`asset-status ${asset.status}`}>{statusLabel[asset.status]}</span><h3>{asset.title}</h3><p>{asset.generator} · EP {asset.sourceEpisodes.join(", ")} · {asset.durationSeconds.toFixed(1)}s</p><button onClick={()=>void remove(asset)} disabled={busy||["published","publishing","scheduled"].includes(asset.status)}><Trash2/> Delete hook</button>{["published","publishing","scheduled"].includes(asset.status)&&<small>Active publishing assets cannot be deleted.</small>}</div></div>}</div>)}<div className="hook-pagination"><button disabled={page===1} onClick={()=>setPage(value=>value-1)}><ChevronLeft/> Previous</button><span>{page} / {pages}</span><button disabled={page===pages} onClick={()=>setPage(value=>value+1)}>Next <ChevronRight/></button></div></section>
  <details className="hook-generator" open><summary><div><span>02 · Generate tools</span><h2>Create hooks</h2></div><small>Built-in generator and Vizard are two ways to create the same saved Hook asset.</small></summary><div className="generator-tabs"><button className={method==="built-in"?"active":""} onClick={()=>setMethod("built-in")}><Scissors/> Built-in</button><button className={method==="vizard"?"active":""} onClick={()=>setMethod("vizard")}><Play/> Vizard</button></div>{method==="vizard"?<VizardStudio sources={sources}/>:<div className="built-in-generator"><label><b>Drama</b><select value={sourceId} onChange={event=>{setSourceId(event.target.value);setEpisodes([])}}>{sources.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div><b>Episodes · up to 5</b><div className="generator-episodes">{source?.episodes.map(episode=><label className={episodes.includes(episode.episodeNumber)?"selected":""} key={episode.episodeNumber}><input type="checkbox" checked={episodes.includes(episode.episodeNumber)} onChange={()=>toggleEpisode(episode.episodeNumber)}/>EP {episode.episodeNumber}{source.analyzedEpisodes.includes(episode.episodeNumber)&&<Check/>}</label>)}</div></div><details className="direction-options"><summary>Advanced direction <small>Optional</small></summary><textarea value={direction} onChange={event=>setDirection(event.target.value)} maxLength={1200} placeholder="想突出的重点、对白、情绪或需要避开的内容…"/><small>{direction.length}/1200</small></details><button className="generate-submit" onClick={()=>void generate()} disabled={busy||!episodes.length}>{busy?<LoaderCircle className="spin"/>:<Scissors/>}{busy?"Starting…":"Generate & auto-save"}</button>{job&&<div className={`generation-status ${job.status}`}><b>{job.status.replaceAll("_"," ")}</b><span>{job.progress}%</span>{job.errorMessage&&<small>{job.errorMessage}</small>}</div>}{error&&<div className="form-error">{error}</div>}</div>}</details>
 </div>
}
