"use client";

import {Ban,Check,Film,LoaderCircle,RefreshCw,Scissors,UploadCloud} from "lucide-react";
import {useEffect,useMemo,useState} from "react";

type Source={id:string;title:string;slug:string;episodes:{episodeNumber:number;videoUrl:string}[]};
type DirectionEvidence={matched?:string[];missing?:string[];excluded?:string[]};
type Candidate={id:string;rank:number;title:string;hookType:string;sourceRanges:{episodeNumber:number;start:number;end:number}[];score:number;scoreComponents:Record<string,number>;rationale:string;riskLevel:string;directionMatchScore?:number;directionEvidence?:DirectionEvidence;coverSourceTimestamp:number;draftUrl?:string};
type Job={id:string;sourceEpisodes:number[];creativeDirection?:string;createdAt:string;status:"queued"|"downloading"|"transcribing"|"analyzing"|"rendering"|"review_ready"|"no_result"|"failed"|"canceled";progress:number;errorMessage?:string;retryCount:number;maxRetries:number;candidates:Candidate[]};
const terminal=new Set(["review_ready","no_result","failed","canceled"]);

export function HookStudio({sources,initialSourceId}:{sources:Source[];initialSourceId?:string}){
 const [sourceId,setSourceId]=useState(sources.some(item=>item.id===initialSourceId)?initialSourceId!:sources[0]?.id||"");
 const source=sources.find(item=>item.id===sourceId);
 const [count,setCount]=useState(Math.min(5,source?.episodes.length||1));
 const [direction,setDirection]=useState("");
 const [job,setJob]=useState<Job|null>(null);
 const [history,setHistory]=useState<Job[]>([]);
 const [restoring,setRestoring]=useState(true);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState("");
 const [saved,setSaved]=useState<string[]>([]);
 const selected=useMemo(()=>source?.episodes.slice(0,count)||[],[source,count]);

 useEffect(()=>{let active=true;setRestoring(true);fetch(`/api/admin/hooks/jobs?dramaId=${encodeURIComponent(sourceId)}`,{cache:"no-store"}).then(response=>response.json().then(json=>({ok:response.ok,json}))).then(({ok,json})=>{if(!active)return;if(!ok)throw new Error(json.message||"Could not restore jobs");const jobs:Job[]=json.jobs||[];setHistory(jobs);setJob(jobs[0]||null);setDirection(jobs[0]?.creativeDirection||"");if(jobs[0]?.sourceEpisodes?.length)setCount(Math.min(5,jobs[0].sourceEpisodes.length))}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Could not restore jobs")}).finally(()=>{if(active)setRestoring(false)});return()=>{active=false}},[sourceId]);
 useEffect(()=>{if(!job||terminal.has(job.status))return;const timer=window.setInterval(async()=>{try{const response=await fetch(`/api/admin/hooks/jobs?id=${encodeURIComponent(job.id)}`,{cache:"no-store"});const json=await response.json();if(response.ok){setJob(json.job);setHistory(items=>items.map(item=>item.id===json.job.id?json.job:item))}}catch{}},2500);return()=>window.clearInterval(timer)},[job]);

 function selectJob(next:Job|null){setJob(next);setDirection(next?.creativeDirection||"");setSaved([])}
 function changeSource(id:string){setSourceId(id);const next=sources.find(item=>item.id===id);setCount(Math.min(5,next?.episodes.length||1));setDirection("");setJob(null);setHistory([]);setError("");setSaved([])}
 async function createJob(){if(!source||!selected.length)return;setBusy(true);setError("");try{const response=await fetch("/api/admin/hooks/jobs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dramaId:source.id,episodeNumbers:selected.map(item=>item.episodeNumber),settings:{maxHooks:2,coverDuration:.1,hookTitle:false,creativeDirection:direction}})});const json=await response.json();if(!response.ok)throw new Error(json.message||"Could not create job");setJob(json.job);setHistory(items=>[json.job,...items.filter(item=>item.id!==json.job.id)])}catch(reason){setError(reason instanceof Error?reason.message:"Could not create job")}finally{setBusy(false)}}
 async function action(value:"cancel"|"retry"){if(!job)return;setBusy(true);setError("");try{const response=await fetch(`/api/admin/hooks/jobs/${job.id}/action`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:value})});const json=await response.json();if(!response.ok)throw new Error(json.message||"Could not update job");setJob(json.job)}catch(reason){setError(reason instanceof Error?reason.message:"Could not update job")}finally{setBusy(false)}}
 async function save(candidate:Candidate){if(!job)return;setBusy(true);setError("");try{const response=await fetch(`/api/admin/hooks/jobs/${job.id}/candidates/${candidate.id}/save`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:candidate.title})});const json=await response.json();if(!response.ok)throw new Error(json.message||"Could not save hook");setSaved(items=>[...items,candidate.id])}catch(reason){setError(reason instanceof Error?reason.message:"Could not save hook")}finally{setBusy(false)}}

 if(!sources.length)return <div className="admin-empty"><Film/><h2>No published dramas</h2></div>;
 return <div className="hook-studio"><section className="hook-builder"><span>01 · Source & durable job</span>
  <label><b>Drama</b><select value={sourceId} onChange={event=>changeSource(event.target.value)} disabled={busy||Boolean(job&&!terminal.has(job.status))}>{sources.map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label>
  {history.length>0&&<label><b>Previous jobs</b><select value={job?.id||""} onChange={event=>selectJob(history.find(item=>item.id===event.target.value)||null)}>{history.map(item=><option value={item.id} key={item.id}>{new Date(item.createdAt).toLocaleString()} · {item.status.replaceAll("_"," ")} · EP {item.sourceEpisodes.join(", ")}</option>)}</select></label>}
  <label><b>Analyze first episodes</b><select value={count} onChange={event=>setCount(Number(event.target.value))} disabled={busy||Boolean(job&&!terminal.has(job.status))}>{source?.episodes.slice(0,5).map((_,index)=><option value={index+1} key={index+1}>First {index+1} episode{index?"s":""}</option>)}</select></label>
  <div className="episode-pills">{selected.map(item=><span key={item.episodeNumber}>EP {item.episodeNumber}</span>)}</div>
  <label className="hook-direction"><b>Hook direction / 想突出的重点</b><textarea value={direction} onChange={event=>setDirection(event.target.value)} maxLength={1200} disabled={busy||Boolean(job)} placeholder="例如：突出禁忌暧昧、嫉妒和带双关的对白；保持平台安全；不要揭露结局；停在亲密动作完成之前。"/><small>{direction.length}/1200 · 留空时使用默认 grounded style。Direction 决定找什么，质量评分决定是否值得剪。</small></label>
  <div className="cover-rule"><b>Frame-zero cover · 0.10 seconds</b><p>Three frames at 30 fps are encoded as the true opening keyframe. The narrative audio starts with the main clip.</p></div>
  {restoring?<div className="hook-placeholder"><LoaderCircle className="spin"/><b>Restoring recent jobs…</b></div>:!job?<button className="save-draft" onClick={()=>void createJob()} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Scissors/>}{busy?"Creating job…":"Start making hooks"}</button>:<div className="hook-job"><div><b>{job.status.replaceAll("_"," ")}</b><span>{job.progress}%</span></div><i style={{width:`${job.progress}%`}}/><small>Job {job.id}</small>{terminal.has(job.status)&&<button onClick={()=>selectJob(null)} disabled={busy}><Scissors/> New job</button>}{!terminal.has(job.status)&&<button onClick={()=>void action("cancel")} disabled={busy}><Ban/> Cancel</button>}{(job.status==="failed"||job.status==="canceled")&&job.retryCount<job.maxRetries&&<button onClick={()=>void action("retry")} disabled={busy}><RefreshCw/> Retry safely</button>}</div>}
  {error&&<div className="form-error">{error}</div>}
  </section><section className="hook-results"><span>02 · Review</span>{!job?<div className="hook-placeholder"><Film/><b>Up to two qualified hooks</b><p>Recent jobs and their exact direction restore automatically.</p></div>:job.status==="no_result"?<div className="hook-placeholder"><Film/><b>No grounded candidate matched the direction and quality gate</b></div>:job.status==="failed"?<div className="form-error">{job.errorMessage||"Worker failed safely."}</div>:job.candidates.length?job.candidates.map(candidate=><article key={candidate.id}><div><b>HOOK {candidate.rank} · {candidate.title}</b><small>{candidate.hookType} · score {candidate.score} · risk {candidate.riskLevel}{candidate.directionMatchScore!=null?` · direction ${candidate.directionMatchScore}`:""}</small></div>{candidate.draftUrl&&<video src={candidate.draftUrl} controls preload="metadata" playsInline/>}<p>{candidate.rationale}</p>{candidate.directionMatchScore!=null&&candidate.directionEvidence&&<small>Matched: {candidate.directionEvidence.matched?.join(", ")||"none"}{candidate.directionEvidence.excluded?.length?` · Excluded: ${candidate.directionEvidence.excluded.join(", ")}`:""}{candidate.directionEvidence.missing?.length?` · Missing: ${candidate.directionEvidence.missing.join(", ")}`:""}</small>}<small>{candidate.sourceRanges.map(range=>`EP ${range.episodeNumber} ${range.start.toFixed(1)}–${range.end.toFixed(1)}s`).join(" · ")} · cover {candidate.coverSourceTimestamp.toFixed(2)}s</small>{candidate.draftUrl&&<button onClick={()=>void save(candidate)} disabled={busy||saved.includes(candidate.id)}>{saved.includes(candidate.id)?<Check/>:<UploadCloud/>}{saved.includes(candidate.id)?"Saved to R2":"Approve & save to R2"}</button>}</article>):<div className="hook-placeholder"><LoaderCircle className={terminal.has(job.status)?"":"spin"}/><b>{job.status.replaceAll("_"," ")}</b><p>{terminal.has(job.status)?"No reviewable drafts were returned.":"The independent worker owns the long-running media work."}</p></div>}</section></div>
}
