"use client";
import { useEffect, useState } from "react";

type Row = { platform: string; hashtag: string; usage_count: number; average_views: number; median_views: number; viral_rate: number; relevance_score: number; score: number; source: string };

export function OpportunityDashboard() {
  const [query, setQuery] = useState("short drama");
  const [platform, setPlatform] = useState("all");
  const [rows, setRows] = useState<Row[]>([]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  async function load(refresh = false) { setBusy(true); setMessage(""); try { const suffix = refresh ? "?refresh=true" : platform === "all" ? "" : `?platform=${platform}`; const response = await fetch(`/api/admin/opportunity/hashtags${suffix}`, { cache: "no-store" }); const json = await response.json(); if (!response.ok) throw new Error(json.message); setRows(json.result.rows || json.result || []); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not load hashtag performance"); } finally { setBusy(false); } }
  async function crawl() { setBusy(true); setMessage(""); try { const response = await fetch("/api/admin/opportunity/youtube", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ query, maxResults: 25 }) }); const json = await response.json(); if (!response.ok) throw new Error(json.message); setMessage(`Imported ${json.result.posts} posts and ${json.result.snapshots} snapshots.`); await load(true); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not crawl YouTube"); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  return <div className="opportunity-dashboard"><section className="panel opportunity-controls"><div><span>01 · Source</span><h2>Discover short-drama signals</h2><p>YouTube Data API is the first connected source. Hashtag scores show their data source and fallback state.</p></div><div className="opportunity-actions"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="short drama revenge"/><button onClick={() => void crawl()} disabled={busy || query.trim().length < 2}>{busy ? "Working…" : "Import YouTube"}</button><select value={platform} onChange={(event) => { setPlatform(event.target.value); void load(false); }}><option value="all">All platforms</option><option value="youtube">YouTube</option><option value="tiktok">TikTok</option><option value="instagram">Instagram</option></select><button className="secondary" onClick={() => void load(true)} disabled={busy}>Refresh scores</button></div>{message && <p className="form-message">{message}</p>}</section><section className="panel opportunity-table"><div className="panel-head"><div><span>02 · Hashtag Intelligence</span><h2>Performance ranking</h2></div><small>{rows.length} records</small></div>{rows.length ? <table><thead><tr><th>Hashtag</th><th>Platform</th><th>Score</th><th>Median views</th><th>Viral rate</th><th>Relevance</th><th>Source</th></tr></thead><tbody>{rows.map((row) => <tr key={`${row.platform}-${row.hashtag}`}><td><b>#{row.hashtag}</b><small>{row.usage_count} posts · avg {Math.round(row.average_views).toLocaleString()}</small></td><td>{row.platform}</td><td><strong>{Number(row.score).toFixed(1)}</strong></td><td>{Math.round(row.median_views).toLocaleString()}</td><td>{Number(row.viral_rate).toFixed(1)}%</td><td>{Number(row.relevance_score).toFixed(1)}</td><td>{row.source}</td></tr>)}</tbody></table> : <div className="opportunity-empty"><b>No performance snapshots yet.</b><span>Import YouTube posts, then refresh scores.</span></div>}</section></div>;
}
