"use client";
import {Check,CloudUpload,Copy,LoaderCircle,Send,ShieldCheck} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {PublishTimePicker} from "@/components/admin/publish-time-picker";
type Hook={id:string;title:string;sourceEpisodes:number[];videoUrl:string;durationSeconds:number};
type Source={id:string;title:string;slug:string;language:string;episodes:{episodeNumber:number;videoUrl:string}[];hooks:Hook[]};
type Pack={source:string;hook:string;caption:string};
type Package={id:string;dramaSlug:string;episodeNumber:number;videoUrl:string;videoKind:string;videoLabel?:string;status:string;platforms:Pack[];createdAt:string};
type YAccount={id:string;name:string;platform:string;status:number};
const options=[["tiktok","TikTok"],["instagram","Instagram"],["youtube","YouTube"],["facebook","Facebook"],["x","X (CSV fallback)"]] as const;
const yNames:Record<string,string>={tiktok:"TikTok",instagram:"Instagram",youtube:"Youtube",facebook:"Facebook"};
export function PublishCenter({sources,yixiaoerReady}:{sources:Source[];yixiaoerReady:boolean}){
 const [sourceId,setSourceId]=useState(sources[0]?.id||"");const source=sources.find(x=>x.id===sourceId);const [kind,setKind]=useState<"original"|"hook"|"upload">("original");const [asset,setAsset]=useState("");const [videoUrl,setVideoUrl]=useState(source?.episodes[0]?.videoUrl||"");const [platforms,setPlatforms]=useState<string[]>(["tiktok","youtube","facebook"]);const [account,setAccount]=useState("");const [campaign,setCampaign]=useState("");const [scheduledAt,setScheduledAt]=useState("");const [created,setCreated]=useState<Package|null>(null);const [recent,setRecent]=useState<Package[]>([]);const [busy,setBusy]=useState(false);const [uploading,setUploading]=useState(false);const [progress,setProgress]=useState(0);const [error,setError]=useState("");const [copied,setCopied]=useState("");const [accounts,setAccounts]=useState<YAccount[]>([]);const [accountIds,setAccountIds]=useState<Record<string,string>>({});const [connectionBusy,setConnectionBusy]=useState(false);const [validated,setValidated]=useState(false);
 useEffect(()=>{fetch("/api/admin/publish-packages").then(async r=>r.ok?(await r.json()).packages:[]).then(setRecent).catch(()=>{})},[]);
 const selectedEpisode=source?.episodes.find(x=>String(x.episodeNumber)===asset)||source?.episodes[0];const selectedHook=source?.hooks.find(x=>x.id===asset);const episodeNumber=kind==="hook"?(selectedHook?.sourceEpisodes[0]||1):(selectedEpisode?.episodeNumber||1);const videoLabel=kind==="hook"?selectedHook?.title:kind==="original"?`EP ${episodeNumber}`:"Manual upload";const allCopy=useMemo(()=>created?.platforms.map(p=>`${p.source.toUpperCase()}\n${p.caption}`).join("\n\n")||"",[created]);
 function resetFor(id:string,nextKind:"original"|"hook"|"upload"="original"){const next=sources.find(x=>x.id===id);setSourceId(id);setKind(nextKind);if(nextKind==="hook"&&next?.hooks[0]){setAsset(next.hooks[0].id);setVideoUrl(next.hooks[0].videoUrl)}else{setAsset(String(next?.episodes[0]?.episodeNumber||""));setVideoUrl(nextKind==="original"?next?.episodes[0]?.videoUrl||"":"")}setCreated(null);setValidated(false)}
 function changeAsset(value:string){setAsset(value);setVideoUrl(kind==="original"?source?.episodes.find(x=>String(x.episodeNumber)===value)?.videoUrl||"":source?.hooks.find(x=>x.id===value)?.videoUrl||"");setCreated(null);setValidated(false)}
 async function upload(file:File){if(!source)return;setUploading(true);setError("");try{const p=await fetch("/api/admin/uploads/presign",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({fileName:file.name,contentType:file.type||"video/mp4",size:file.size,slug:source.slug,kind:"social"})});const data=await p.json();if(!p.ok)throw new Error(data.message);await new Promise<void>((resolve,reject)=>{const x=new XMLHttpRequest();x.open("PUT",data.uploadUrl);x.setRequestHeader("Content-Type",file.type||"video/mp4");x.upload.onprogress=e=>e.lengthComputable&&setProgress(Math.round(e.loaded/e.total*100));x.onload=()=>x.status<300?resolve():reject(new Error("R2 upload failed"));x.onerror=()=>reject(new Error("R2 upload failed"));x.send(file)});setVideoUrl(data.publicUrl);setProgress(100)}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setUploading(false)}}
 async function create(){if(!source||!videoUrl||!platforms.length)return;setBusy(true);setError("");try{const r=await fetch("/api/admin/publish-packages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({dramaSlug:source.slug,episodeNumber,videoUrl,videoKind:kind,videoLabel,hookClipId:kind==="hook"?selectedHook?.id:undefined,account,campaign,scheduledAt:scheduledAt?new Date(scheduledAt).toISOString():undefined,platforms})});const j=await r.json();if(!r.ok)throw new Error(j.message);setCreated(j.package);setRecent(x=>[j.package,...x]);await loadAccounts()}catch(e){setError(e instanceof Error?e.message:"Could not create package")}finally{setBusy(false)}}
 async function loadAccounts(){if(!yixiaoerReady)return;setConnectionBusy(true);try{const r=await fetch("/api/admin/yixiaoer/accounts");const j=await r.json();if(!r.ok)throw new Error(j.message);setAccounts(j.accounts);const next:Record<string,string>={};for(const platform of platforms){const matches=j.accounts.filter((a:YAccount)=>a.platform.toLowerCase()===yNames[platform]?.toLowerCase());if(matches.length===1)next[platform]=matches[0].id}setAccountIds(next)}catch(e){setError(e instanceof Error?e.message:"Could not load accounts")}finally{setConnectionBusy(false)}}
 async function yAction(action:"validate"|"publish"){if(!created)return;if(action==="publish"&&!window.confirm("This will publish immediately to the selected live social accounts. Continue?"))return;setConnectionBusy(true);setError("");try{const r=await fetch(`/api/admin/publish-packages/${created.id}/yixiaoer`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,confirm:action==="publish",accounts:accountIds})});const j=await r.json();if(!r.ok)throw new Error(j.message);setCreated(j.package);setValidated(action==="validate")}catch(e){setError(e instanceof Error?e.message:"Yixiaoer operation failed")}finally{setConnectionBusy(false)}}
 async function copy(text:string,key:string){await navigator.clipboard.writeText(text);setCopied(key);setTimeout(()=>setCopied(""),1200)}
 if(!sources.length)return <div className="admin-empty"><Send/><h2>No published dramas</h2></div>;
 return <div className="publish-center">
  <section className="publish-compose"><span>01 · Exact video asset</span><label><b>Drama</b><select value={sourceId} onChange={e=>resetFor(e.target.value)}>{sources.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label><div className="asset-kind">{(["original","hook","upload"] as const).map(x=><button className={kind===x?"selected":""} key={x} onClick={()=>resetFor(sourceId,x)}>{x==="original"?"Original episode":x==="hook"?"Saved hook":"Manual upload"}</button>)}</div>{kind!=="upload"&&<label><b>Specific video</b><select value={asset||String(kind==="original"?source?.episodes[0]?.episodeNumber:source?.hooks[0]?.id||"")} onChange={e=>changeAsset(e.target.value)}>{kind==="original"?source?.episodes.map(x=><option value={x.episodeNumber} key={x.episodeNumber}>EP {x.episodeNumber}</option>):source?.hooks.map(x=><option value={x.id} key={x.id}>{x.title} · {x.durationSeconds}s</option>)}</select></label>}<div className="video-source"><b>{videoLabel}</b><code>{videoUrl||"No video selected"}</code></div>{videoUrl&&<video className="publish-preview" src={videoUrl} controls preload="metadata"/>}{kind==="upload"&&<label className="social-upload"><input type="file" accept="video/mp4,video/quicktime" onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/><CloudUpload/><b>{uploading?`Uploading · ${progress}%`:"Upload a finished video to R2"}</b></label>}</section>
  <section className="publish-compose"><span>02 · Distribution</span><div className="platform-picker"><span>Platforms</span><div>{options.map(([v,l])=><label className={platforms.includes(v)?"selected":""} key={v}><input type="checkbox" checked={platforms.includes(v)} onChange={()=>{setPlatforms(x=>x.includes(v)?x.filter(p=>p!==v):[...x,v]);setCreated(null);setValidated(false)}}/>{l}</label>)}</div></div><div className="publish-grid"><label><b>Account label · optional</b><input value={account} onChange={e=>setAccount(e.target.value)}/></label><label><b>Campaign · optional</b><input value={campaign} onChange={e=>setCampaign(e.target.value)}/></label><label><b>Publish time · tracking only</b><PublishTimePicker value={scheduledAt} onChange={setScheduledAt}/></label></div><button className="save-draft" onClick={()=>void create()} disabled={!videoUrl||!platforms.length||busy}>{busy?<LoaderCircle className="spin"/>:<Send/>}{busy?"Building package…":"Generate publish package"}</button>{error&&<div className="form-error">{error}</div>}</section>
  {created&&<section className="publish-results"><div className="pack-heading"><div><span>{created.status==="published"?"Published live":validated||created.status==="ready"?"Uploaded & dry-run passed":"Package generated · not uploaded"}</span><b>{source?.title} · {created.videoLabel}</b></div><button onClick={()=>void copy(allCopy,"all")}>{copied==="all"?<Check/>:<Copy/>} Copy all</button></div>{created.platforms.map(pack=><article key={pack.source}><b>{pack.source}</b><strong>{pack.hook}</strong><p>{pack.caption}</p></article>)}<div className={`metricool-state ${yixiaoerReady?"ready":"pending"}`}><div><b>{yixiaoerReady?"Yixiaoer connected":"Yixiaoer API key missing"}</b><span>{created.status==="published"?"Live publishing completed":accounts.length?`${accounts.length} publishing account(s) available`:"Bind social accounts in Yixiaoer, then refresh"}</span></div><button onClick={()=>void loadAccounts()} disabled={connectionBusy||created.status==="published"}>Refresh accounts</button></div>{created.status!=="published"&&Object.keys(yNames).filter(p=>platforms.includes(p)).map(p=><label className="yixiaoer-account" key={p}><b>{yNames[p]} account</b><select value={accountIds[p]||""} onChange={e=>{setAccountIds(x=>({...x,[p]:e.target.value}));setValidated(false)}}><option value="">Choose account</option>{accounts.filter(a=>a.platform.toLowerCase()===yNames[p].toLowerCase()).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label>)}{created.status!=="published"&&<div className="yixiaoer-actions"><button onClick={()=>void yAction("validate")} disabled={connectionBusy||!yixiaoerReady}><ShieldCheck/> {connectionBusy?"Working…":"Upload, validate & dry-run"}</button><button className="publish-live" onClick={()=>void yAction("publish")} disabled={connectionBusy||!validated}><Send/> Confirm live publish</button></div>}</section>}
  {recent.length>0&&<section className="publish-history"><span>Recent publish packages</span>{recent.slice(0,10).map(x=><div key={x.id}><b>{x.dramaSlug} · {x.videoLabel||`EP ${x.episodeNumber}`}</b><small>{x.videoKind} · {x.status}</small></div>)}</section>}
 </div>
}
