"use client";
import {CheckCircle2,KeyRound,LoaderCircle} from "lucide-react";
import {useState} from "react";

export function YixiaoerKeyRotation({configured,updatedAt}:{configured:boolean;updatedAt:string|null}){
 const [key,setKey]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");const [savedAt,setSavedAt]=useState(updatedAt);
 async function rotate(event:React.FormEvent){event.preventDefault();if(!key.trim())return;setBusy(true);setError("");setMessage("");try{const response=await fetch("/api/admin/settings/yixiaoer-key",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({apiKey:key.trim()})});const json=await response.json();if(!response.ok)throw new Error(json.message||"Could not rotate key");setKey("");setSavedAt(json.updatedAt);setMessage(`Verified and activated · ${json.accountCount} online account(s)`)}catch(reason){setError(reason instanceof Error?reason.message:"Could not rotate key")}finally{setBusy(false)}}
 return <section className="panel key-rotation-card"><div className="repository-icon"><KeyRound/></div><span>Publishing credential</span><h2>Rotate Yixiaoer API Key</h2><p>The new key is verified against Yixiaoer before it replaces the active credential. It is encrypted at rest and takes effect immediately—no Vercel rebuild required.</p><div className="key-state"><CheckCircle2/><div><b>{configured||savedAt?"Runtime key configured":"Using deployment fallback key"}</b><small>{savedAt?`Last rotated ${new Date(savedAt).toLocaleString()}`:"Add a fresh key before the current 24-hour key expires."}</small></div></div><form onSubmit={rotate}><label><b>New API Key</b><input type="password" autoComplete="off" value={key} onChange={event=>setKey(event.target.value)} placeholder="Paste a newly generated Yixiaoer API Key"/></label><button disabled={busy||!key.trim()}>{busy?<LoaderCircle className="spin"/>:<KeyRound/>}{busy?"Verifying…":"Verify & activate key"}</button></form>{message&&<div className="form-success"><CheckCircle2/><div><b>Key activated</b><span>{message}</span></div></div>}{error&&<div className="form-error">{error}</div>}</section>
}
