alter table public.hook_clips add column if not exists job_id uuid references public.hook_generation_jobs(id);
alter table public.hook_clips add column if not exists candidate_id uuid unique references public.hook_candidates(id);
alter table public.hook_clips add column if not exists drama_id uuid;
alter table public.hook_clips add column if not exists hook_type text not null default 'unknown';
alter table public.hook_clips add column if not exists source_ranges jsonb not null default '[]';
alter table public.hook_clips add column if not exists rendered_ranges jsonb not null default '[]';
alter table public.hook_clips add column if not exists object_key text;
alter table public.hook_clips add column if not exists width integer not null default 1080;
alter table public.hook_clips add column if not exists height integer not null default 1920;
alter table public.hook_clips add column if not exists video_codec text not null default 'h264';
alter table public.hook_clips add column if not exists audio_codec text not null default 'aac';
alter table public.hook_clips add column if not exists size_bytes bigint;
alter table public.hook_clips add column if not exists score numeric(5,2);
alter table public.hook_clips add column if not exists score_components jsonb not null default '{}';
alter table public.hook_clips add column if not exists rationale text;
alter table public.hook_clips add column if not exists risk_level text not null default 'low';
alter table public.hook_clips add column if not exists cover_source_timestamp numeric(10,3);
alter table public.hook_clips add column if not exists transcript_version text;
alter table public.hook_clips add column if not exists model_version text;
alter table public.hook_clips add column if not exists prompt_version text;
alter table public.hook_clips add column if not exists ranking_version text;
alter table public.hook_clips add column if not exists render_version text;
alter table public.hook_clips add column if not exists review_state text not null default 'approved';
alter table public.hook_clips add column if not exists reviewed_by text;
alter table public.hook_clips add column if not exists reviewed_at timestamptz;
alter table public.hook_clips add column if not exists updated_at timestamptz not null default now();

update public.hook_clips set object_key=coalesce(object_key,'legacy/'||id::text||'.mp4') where object_key is null;
alter table public.hook_clips alter column object_key set not null;
